Anna Oriekhova w1 browsers
HackYourHomework/Homework-class40 pull request #40
Opened 2022-10-04 22:27 UTC by anutka2610

2022-10-10 11:05 UTC, robvk requested changes
Please finish exercise 5 and fix the last problems.

2022-10-12 16:36 UTC, anutka2610 commented on 2-Browsers/Week1/homework/ex2-aboutMe/style.css
> +    color: red;
this is done

2022-10-12 16:37 UTC, anutka2610 commented on 2-Browsers/Week1/homework/ex2-aboutMe/index.js
> +   allLi[i].setAttribute('class', 'list-item');
this is done

2022-10-12 17:53 UTC, anutka2610 commented on 2-Browsers/Week1/test-reports/ex1-bookList.fail.txt
> +    ✕ HTML should be syntactically valid (113 ms)
It's done. Some tome difficult to understand where mistake) just if you will read test cearful)

2022-10-18 10:45 UTC, robvk requested changes
Nice changes, still missing a complete exercise 5 and one more problem in exercise 4

2022-10-18 10:45 UTC, robvk commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +addCurrentTime();
You don't need to call addCurrentTime() here as it will happen on load as you added it to the window load event. I think it is best to also have the setInterval in the load event.

2022-10-20 08:37 UTC, robvk approved these changes
Some last things I want to give along to you but overal it looks good now. Approved!

2022-10-20 08:37 UTC, robvk commented on 2-Browsers/Week1/homework/ex4-whatsTheTime/index.js
> +setInterval(loadWindow, 1000);
This will call the loadWindow function every second and that function adds an eventListener to the window so each time you are adding more and more listeners. The way I would do it is like this:

```
window.addEventListener('load', () => {
  setInterval(addCurrentTime, 1000);
});
```

This adds the event listener once and once the page has loaded it will start the timer.

2022-10-20 08:37 UTC, robvk commented on 2-Browsers/Week1/homework/ex5-catWalk/index.js
> +   catPosition ===
The `===` here is a little risky, I would go for the `>=` with an extra check to see if the cat has danced already as you are doing arithmetic with screen widths and that can be anything.

2023-01-26 10:19 UTC, closed without merging